#!/usr/bin/env sh

n="$(echo $2 | sed 's/\/$//')"
n="$(echo ${n} | sed 's/\//->/g')"

PROJECT_NAME="f-$(echo ${n} | sed 's/.*>//')"
NEW_WINDOW=$(tmux new-window -t default -P -n ${PROJECT_NAME})

sesh connect $2

killall nnn
